### ISSUE TITLE
[Bug]: DeepDungeonDex fails to load

### ISSUE THREAD

**Issue by belthesar** [wolfcomp/DeepDungeonDex#155]
### Dalamud log

```
11:14:20.718 ERR | Unobserved exception in Task.
11:14:20.718 ERR | System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Collection was modified; enumeration operation may not execute.)
11:14:20.718 ERR |  ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
11:14:20.718 ERR |    at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
11:14:20.718 ERR |    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
11:14:20.718 ERR |    at DeepDungeonDex.Storage.StorageHandler.Save() in /work/repo/DeepDungeonDex/Storage/StorageHandler.cs:line 226
11:14:20.718 ERR |    at DeepDungeonDex.Requests.RefreshFileList(Boolean continuous) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 90
11:14:20.718 ERR |    --- End of inner exception stack trace ---
```

### Steps to reprduce

1. Launch FFXIV with DeepDungeonDex activated.

### Environment

```markdown
- **OS**: Windows 10 22H2 (19045.3448)
- **Dalamud**: 9.0.0.2
```

### Anything else?

Haven't personally tried loading in a Deep Dungeon, just checking my XL Logs while troubleshooting a different issue. Happy to assist with troubleshooting steps if guidance is provided.

**Comment by wolfcomp** [comment]
This is not a fail to load and is only related to saving local files in case you are unable to load from GitHub with the data.
