### ISSUE TITLE
[Bug]: Huge FPS Drops when targeting enemys

### ISSUE THREAD

**Issue by WrathfulMonkey84** [wolfcomp/DeepDungeonDex#69]
### Dalamud log

--------------------------------
08:59:35.921 | ERR [TPie] Font failed to load: Object reference not set to an instance of an object.
--------------------------------
08:59:37.543 | ERR [DalamudRepoBrowser] Failed to load.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DalamudRepoBrowser.DalamudRepoBrowser.ReflectRepos() in D:\a\DalamudRepoBrowser\DalamudRepoBrowser\DalamudRepoBrowser.cs:line 180
   at DalamudRepoBrowser.DalamudRepoBrowser..ctor(DalamudPluginInterface pluginInterface) in D:\a\DalamudRepoBrowser\DalamudRepoBrowser\DalamudRepoBrowser.cs:line 141
--------------------------------
08:59:44.299 | WRN [Penumbra] Penumbra.ApiVersion is outdated. Please use Penumbra.ApiVersions instead.
--------------------------------
08:59:44.303 | WRN [Penumbra] Penumbra.ApiVersion is outdated. Please use Penumbra.ApiVersions instead.
--------------------------------
09:01:24.050 | WRN [PLUGINR] The repository "https://raw.githubusercontent.com/Akurosia/MyCustomDalamudPluginRepoCollection/main/ffxiv_custom_repo.json" tried to replace the plugin "JobIcons", which is already installed through the official repo - this is no longer allowed for security reasons. Please reach out if you have an use case for this.
--------------------------------
09:01:24.055 | ERR [PLUGINR] PluginMaster failed: https://darkarchon.internet-box.ch:8443/plogon/plogonmaster.json
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Dalamud.Plugin.Internal.Types.PluginRepository.ReloadPluginMasterAsync() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\PluginRepository.cs:line 95
--------------------------------
09:08:14.934 | ERR [DeepDungeonDex] Failed to get translated string of 4976 falling back
System.Collections.Generic.KeyNotFoundException: Key 4976 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:08:33.570 | ERR [DeepDungeonDex] Failed to get translated string of 4983 falling back
System.Collections.Generic.KeyNotFoundException: Key 4983 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:08:34.684 | ERR [DeepDungeonDex] Failed to get translated string of 5479 falling back
System.Collections.Generic.KeyNotFoundException: Key 5479 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:11:16.879 | ERR [DeepDungeonDex] Failed to get translated string of 4977 falling back
System.Collections.Generic.KeyNotFoundException: Key 4977 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:12:17.384 | ERR [DeepDungeonDex] Failed to get translated string of 4978 falling back
System.Collections.Generic.KeyNotFoundException: Key 4978 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:12:18.386 | ERR [DeepDungeonDex] Failed to get translated string of 4984 falling back
System.Collections.Generic.KeyNotFoundException: Key 4984 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:14:26.127 | ERR [DeepDungeonDex] Failed to get translated string of 4979 falling back
System.Collections.Generic.KeyNotFoundException: Key 4979 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:24:56.826 | ERR [DeepDungeonDex] Failed to get translated string of 4987 falling back
System.Collections.Generic.KeyNotFoundException: Key 4987 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:31:46.840 | ERR [DeepDungeonDex] Failed to get translated string of 4992 falling back
System.Collections.Generic.KeyNotFoundException: Key 4992 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:33:00.155 | ERR [DeepDungeonDex] Failed to get translated string of 4991 falling back
System.Collections.Generic.KeyNotFoundException: Key 4991 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:34:43.507 | ERR [DeepDungeonDex] Failed to get translated string of 4998 falling back
System.Collections.Generic.KeyNotFoundException: Key 4998 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:36:12.088 | ERR [DeepDungeonDex] Failed to get translated string of 4995 falling back
System.Collections.Generic.KeyNotFoundException: Key 4995 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:37:46.473 | ERR [DeepDungeonDex] Failed to get translated string of 4994 falling back
System.Collections.Generic.KeyNotFoundException: Key 4994 could not be found in dictionary.
   at DeepDungeonDex.Localization.DictionaryExtension.GetString(Dictionary`2 dictionary, String key)
   at DeepDungeonDex.Localization.Locale.GetString(String name)
--------------------------------
09:48:03.668 | ERR [PLUGINR] PluginMaster failed: https://darkarchon.internet-box.ch:8443/plogon/plogonmaster.json
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Dalamud.Plugin.Internal.Types.PluginRepository.ReloadPluginMasterAsync() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\PluginRepository.cs:line 95
--------------------------------
09:48:03.757 | WRN [PLUGINR] The repository "https://raw.githubusercontent.com/Akurosia/MyCustomDalamudPluginRepoCollection/main/ffxiv_custom_repo.json" tried to replace the plugin "JobIcons", which is already installed through the official repo - this is no longer allowed for security reasons. Please reach out if you have an use case for this.
{ } [ Send ]

### Steps to reprduce

The FPS drops do not occur when I have DeepDungenDex disabled.

The FPS drops get bigger from level to level. As soon as an enemy is selected, the FPS drops by 20 to 80%.

Currently I deactivate and reactivate DeepDungeonDex every 10 levels to reset the FPS drops.

Most of the time FFXIV crashes when reactivating DeepDungeonDex.

Here are two screenshots as an example:

![image](https://user-images.githubusercontent.com/118614701/202894014-600ad934-d675-4351-be70-d7250dcadbaf.png)

![image](https://user-images.githubusercontent.com/118614701/202894038-1f1c6952-7728-4d63-854e-c43030c3e097.png)

### Environment

```markdown
- Windows 11
```

**Comment by WrathfulMonkey84** [comment]
I also noticed that my GPU utilization drops from about 90% to below 50%

**Comment by wolfcomp** [comment]
Taken from discord 
![img](https://screenshots.wildwolf.dev/Discord_0b5dbe5bcf.png)
There are way too many factors going on for me to say for certain that this is an isolated issue to DeepDungeonDex or if there are other factors in play to cause this.

**Comment by Aigachu** [comment]
I had this same problem, but after updating to the latest version, it seems to have been fixed.

Went from floors 1 to 180 yesterday and the FPS drops got progressively worse. Now today with the latest version, I've gotten to floor 110 with seemingly no FPS drops.

Will update if I encounter any more but seems like it's fixed to me.
